/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umich.eac;

class eacJNI {
  public final static native long JNICacheFetcher_call(long jarg1, JNICacheFetcher jarg1_, long jarg2);
  public final static native void delete_JNICacheFetcher(long jarg1);

  static {
    System.loadLibrary("eac_native");
  }
}
