/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umich.eac;

import edu.umich.eac.CacheFetcher;

public class JNICacheFetcher implements CacheFetcher<SWIGTYPE_p_void> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JNICacheFetcher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JNICacheFetcher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      eacJNI.delete_JNICacheFetcher(swigCPtr);
    }
    swigCPtr = 0;
  }

  public SWIGTYPE_p_void call(long labels) {
    if (swigCPtr == 0) {
        throw new RuntimeException("ERROR: JNICacheFetcher.call() would segfault");
    }
    long cPtr = eacJNI.JNICacheFetcher_call(swigCPtr, this, labels);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
