/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umich.eac;
import android.util.Log;

public class SWIGTYPE_p_void {
  private int swigCPtr;

  protected SWIGTYPE_p_void(int cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_void() {
    swigCPtr = 0;
  }

  protected static int getCPtr(SWIGTYPE_p_void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
  
  private static String TAG = SWIGTYPE_p_void.class.getName();
  static void forceLoad() {
      Log.d(TAG, "Forced classloading");
  }
}

